#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

x = 1
y = 2
z = 0
u = 0
sum = 0

for i in range (0 ,8 ,1):
    z = x + y
    if (z % 2 == 0):
        sum = sum + z
    u = y + z
    if (u % 2 == 0):
        sum = sum + u
    x = z + u
    if (x % 2 == 0):
        sum = sum + x
    y = u + x
    if (y % 2 == 0):
        sum = sum + y
print(sum + 2)